services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-cooperativa
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"
    volumes:
      - sql_data:/var/opt/mssql

  cooperativa-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: cooperativa-app
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    command: http host.docker.internal:5000 --domain=www.majacom.com
    environment:
      - NGROK_AUTHTOKEN=2t7EYmOIpVTO6O3oDQirNSdAdcT_2GZxzGujqiZnuEWZp83dc
    network_mode: "host"

volumes:
  sql_data:
