version: '3.8'

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - sqlserver
    networks:
      - devnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - devnet

networks:
  devnet:
